### ISSUE TITLE
Обратная связь по тестовому заданию

### ISSUE THREAD

**Issue by a-ovch** [NikulinIlya/todo-list#1]
Илья, привет!

Очень круто, что ты сделал полную версию задания вместе со всеми опциональными пунктами.
К сожалению, не знаком с фреймворком Lumen, надеюсь, что правильно разобрался во всех моментах :)

По оформлению кода всё хорошо - тут мне прокомментировать нечего :)

Касаемо "архитектурного" момента по организации кода, возможно ты итак это делаешь в больших проектах, а не в масштабах тестового: я бы рекомендовал вытаскивать бизнес-логику из контроллера в отдельный класс. Это особенно удобно, когда у этого класса есть несколько потребителей (тех же контроллеров, например) и мы не зависим от какого-то одного конкретного представления данных. 

Также я бы не рекомендовал делать подобные конструкции:

`$todoTask->fill($request->all());`
`return response()->json($todoTask);`

Делаем очень сильную зависимость между форматом запроса/ответа и моделью. В запросе может что-то лишнее оказаться, чего мы бы не хотели, чтобы попало в модель и любое изменение модели потребует изменения запроса/ответа. В таких случаях вводится посредник, который выполняет все преобразования данных (на самом деле выше я про это же и писал). Есть еще такое понятие как anti-corruption level, можешь тоже поизучать, если не знаком.

Хотел еще у тебя уточнить момент по API, который ты спроектировал для этого сервиса. Методы PUT и PATCH оба используются для обновления задачи. Все-таки, по "чистому" REST семантика у них немного разная, предлагаю оставить один. И правильно ли я понял, что в методе обновления я могу прислать пустую строку для названия задачи и она запишется в БД?

Кстати, касаемо архитектуры, если хочешь подробнее узнать как все устроено внутри, можешь [посмотреть доклад одного из наших архитекторов](https://www.youtube.com/watch?v=xT25xiKqPcI&t=1s&ab_channel=iSpringTech).

**Comment by NikulinIlya** [comment]
Добрый день!
Действительно, в рамках задания и микрофреймворка Lumen не стал отделять бизнес-логику отдельно от контроллеров. С докладом обязательно ознакомлюсь, спасибо!
Внес изменения, убрав дублирующий метод PUT, а также закрыл возможность обновления задачи пустой строкой.
